[tool]
[tool.poetry]
authors = ["Your Name <you@example.com>"]
name = "root"
version = "0.0.0"
[tool.poetry.dependencies]
asyncio = "*"
cryptography = "*"
"discord.py" = "*"
dnspython = "==1.16.0"
emoji = "*"
flask = "*"
motor = "*"
python = "^3.7"
